server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    #active: aggregation
    active: dev
  data:
    redis:
      host: 192.168.52.128
      port: 6379
      password: hxj163213518
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848