server:
  port: 8003

spring:
  application:
    name: short-link-aggregation
  datasource:
    # ShardingSphere ? Driver ???????????????
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere ??????
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 192.168.52.128
      port: 6379
      password: hxj163213518
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

aggregation:
  remote-url: http://127.0.0.1:${server.port}

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
  domain:
    default: nurl.ink:8003
  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

